# Generated by Django 4.1.2 on 2022-10-20 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musicapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Songs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=50)),
                ("Date_Released", models.CharField(max_length=50)),
                ("Likes", models.CharField(max_length=50)),
                ("artiste_id", models.CharField(max_length=50)),
            ],
        ),
    ]
